version: '2.1'

services:
  flask-boilerplate:
    image: flask-boilerplate
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./:/usr/src/app
    depends_on:
      - database
  database:
    image: postgres:9
    env_file: .env
    expose:
      - 5432